import Link from 'next/link'
import { ArrowLeft, ArrowRight, Check, ChevronRight, Clock3, Lock, Play, ShieldCheck } from 'lucide-react'
import { CyberHeader } from '@/components/cyber-header'
import { getTrack, tracks } from '@/lib/learning-data'

export function generateStaticParams() { return tracks.map((track) => ({ slug: track.slug })) }
export default async function TrackPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const track = getTrack(slug)
  if (!track) return <div />
  const totalLessons = track.modulesData.reduce((total, module) => total + module.lessons.length, 0)
  return <main className="app-shell"><CyberHeader /><section className="track-detail-hero"><div className="content-wrap"><Link href="/trilhas" className="back-link"><ArrowLeft size={16} /> Todas as trilhas</Link><div className="detail-grid"><div><div className="eyebrow">{track.category} / {track.difficulty}</div><h1>{track.title}</h1><p>{track.description}</p><div className="detail-stats"><span><strong>{track.modules}</strong> módulos</span><span><strong>{track.lessons}</strong> aulas</span><span><strong>{track.duration}</strong> duração</span></div></div><div className="track-progress-card"><div className="progress-ring"><strong>{track.progress}%</strong></div><div><span>Seu progresso</span><h3>{track.progress === 100 ? 'Trilha concluída' : 'Continue de onde parou'}</h3></div><div className="progress-track"><span style={{ width: `${track.progress}%`, background: track.color }} /></div></div></div></div></section><section className="content-wrap curriculum"><div className="section-heading"><div><div className="eyebrow">Conteúdo da trilha</div><h2>O caminho para sua evolução</h2></div><span>{totalLessons} aulas no total</span></div><div className="module-list">{track.modulesData.map((module, index) => <article className="module-card" key={module.title}><div className="module-header"><div className="module-number">0{index + 1}</div><div><h3>{module.title}</h3><span>{module.lessons.length} aulas</span></div><ChevronRight size={20} /></div><div className="lesson-list">{module.lessons.map((lesson) => <Link href={`/aulas/${lesson.slug}`} className={`lesson-row lesson-${lesson.status}`} key={lesson.slug}>{lesson.status === 'completed' ? <span className="lesson-icon completed"><Check size={15} /></span> : lesson.status === 'locked' ? <span className="lesson-icon locked"><Lock size={14} /></span> : <span className="lesson-icon current"><Play size={13} /></span>}<span className="lesson-title">{lesson.title}{lesson.status === 'current' && <small>Em andamento</small>}</span><span className="lesson-duration"><Clock3 size={14} /> {lesson.duration}</span><ChevronRight size={16} /></Link>)}</div></article>)}</div></section></main>
}
