import Link from 'next/link'
import type { ReactNode } from 'react'
import { CyberHeader } from '@/components/cyber-header'
import { DashboardNavigation } from '@/components/dashboard-navigation'
import { SiteFooter } from '@/components/site-footer'
import './politicas.css'
import '../footer.css'

const terms = [
  ['aceitacao', 'Aceitação dos Termos', <>Ao acessar, criar uma conta ou utilizar o CyberEduca+, você declara que leu e concorda com estes Termos de Uso e com a Política de Privacidade. Se não concordar, não utilize a plataforma. Quando o consentimento de responsável legal for exigido, o uso dependerá dessa autorização.</>],
  ['finalidade', 'Finalidade da plataforma', <>O CyberEduca+ é uma plataforma educacional de cibersegurança com trilhas, aulas, quizzes, acompanhamento de progresso e simulações fictícias de phishing. O conteúdo possui finalidade informativa e pedagógica e não substitui aconselhamento profissional, jurídico ou técnico individualizado.</>],
  ['conta', 'Cadastro e conta', <><p>O usuário deve fornecer informações verdadeiras, completas e atualizadas, manter suas credenciais em sigilo e comunicar qualquer uso não autorizado. Cada conta é pessoal e não pode ser cedida.</p><p>A plataforma poderá solicitar confirmação de identidade para proteger a conta, atender direitos ou investigar atividades suspeitas.</p></>],
  ['uso-aceitavel', 'Uso aceitável', <><p>É proibido usar o CyberEduca+ para:</p><ul><li>praticar fraude, phishing real, invasão, assédio ou qualquer atividade ilícita;</li><li>tentar acessar contas, áreas administrativas, sistemas ou dados sem autorização;</li><li>copiar, automatizar, explorar vulnerabilidades ou sobrecarregar o serviço;</li><li>inserir código malicioso ou utilizar o conteúdo para prejudicar terceiros;</li><li>violar direitos autorais, privacidade ou outros direitos de terceiros.</li></ul></>],
  ['simulacoes', 'Simulações de phishing', <>Os cenários de phishing são fictícios e destinados exclusivamente ao aprendizado. O usuário não deve reproduzi-los contra pessoas ou organizações. Resultados, classificações e explicações são educacionais e podem não representar todas as técnicas existentes.</>],
  ['conteudo', 'Conteúdo e propriedade intelectual', <>Textos, interfaces, ilustrações, marcas, aulas, quizzes, cenários e demais materiais pertencem ao CyberEduca+ ou a seus respectivos licenciantes. É permitido o uso pessoal e educacional dentro da plataforma. Reprodução, distribuição, adaptação ou exploração comercial dependem de autorização prévia, salvo permissões legais ou licenças expressamente indicadas.</>],
  ['disponibilidade', 'Disponibilidade e alterações', <>A plataforma poderá receber manutenção, correções e atualizações. Funcionalidades podem ser modificadas, suspensas ou descontinuadas mediante comunicação razoável quando isso afetar significativamente o usuário. Não é garantida disponibilidade ininterrupta, especialmente em casos de falha técnica, manutenção ou evento fora de controle razoável.</>],
  ['suspensao', 'Suspensão e encerramento', <>O acesso poderá ser limitado ou suspenso em caso de violação destes Termos, risco à segurança, fraude ou determinação legal. O usuário poderá solicitar o encerramento da conta. Dados associados serão eliminados ou conservados conforme a Política de Privacidade e as obrigações legais aplicáveis.</>],
  ['responsabilidade', 'Responsabilidades', <>O CyberEduca+ adota medidas razoáveis para manter conteúdos corretos e o serviço seguro, mas não responde por decisões tomadas exclusivamente com base no material educacional, por uso indevido da plataforma, por serviços de terceiros ou por danos decorrentes de fato inevitável, respeitados os direitos que não possam ser excluídos pela legislação brasileira.</>],
  ['lei-foro', 'Lei aplicável e solução de conflitos', <>Estes Termos são regidos pelas leis brasileiras, incluindo o Marco Civil da Internet, a LGPD e, quando aplicável, o Código de Defesa do Consumidor. Fica assegurado ao usuário o acesso aos órgãos de defesa do consumidor e ao foro legalmente competente, sem imposição de foro que restrinja direitos obrigatórios.</>],
  ['alteracoes-termos', 'Alterações destes Termos', <>Mudanças relevantes serão informadas de forma destacada na plataforma. A versão vigente indicará a data de atualização. Quando uma alteração exigir novo consentimento, ele será solicitado antes da continuidade do tratamento ou uso correspondente.</>],
]

const privacy = [
  ['controlador', 'Controlador e contato', <>O controlador é o <strong>CyberEduca+</strong>, projeto acadêmico desenvolvido no âmbito da Universidade de Mogi das Cruzes (UMC). Solicitações de privacidade devem ser encaminhadas pelo canal <Link href="/em-breve">Fale conosco</Link>. Antes da publicação definitiva, esse canal deverá identificar o responsável e disponibilizar um meio de contato funcional.</>],
  ['dados-coletados', 'Dados tratados', <><p>Conforme a funcionalidade utilizada, podemos tratar:</p><ul><li>nome, e-mail, identificadores de conta e informações básicas de perfil;</li><li>credenciais protegidas por hash e dados de autenticação e sessão;</li><li>trilhas, aulas acessadas, conclusões e percentual de progresso;</li><li>respostas, tentativas, notas, feedbacks e histórico de quizzes;</li><li>classificações e resultados de simulações fictícias de phishing;</li><li>registros técnicos, como data, horário, endereço IP, dispositivo, navegador e eventos de segurança;</li><li>preferências de cookies e comunicações enviadas ao suporte;</li><li>para administradores, registros de gestão de conteúdos e usuários.</li></ul><p>Não solicitamos dados sensíveis para o funcionamento normal da plataforma. Não insira dados reais de terceiros nos exercícios ou simulações.</p></>],
  ['finalidades-dados', 'Finalidades do tratamento', <><ul><li>criar, autenticar e proteger a conta;</li><li>entregar aulas, trilhas, quizzes e simulações;</li><li>registrar progresso e apresentar histórico e desempenho;</li><li>personalizar a continuidade da aprendizagem;</li><li>prestar suporte e responder solicitações;</li><li>prevenir fraude, abuso e incidentes de segurança;</li><li>gerar métricas agregadas para melhorar o conteúdo e a plataforma;</li><li>cumprir obrigações legais e exercer direitos em processos.</li></ul></>],
  ['bases-legais', 'Bases legais', <>O tratamento poderá ocorrer para executar o contrato e procedimentos solicitados pelo usuário; cumprir obrigação legal ou regulatória; exercer direitos; proteger a vida ou a integridade quando aplicável; atender interesses legítimos, após avaliação de necessidade e impacto; e mediante consentimento quando essa for a base adequada, como em cookies não essenciais. O consentimento pode ser revogado sem afetar tratamentos anteriores lícitos.</>],
  ['cookies', 'Cookies e tecnologias semelhantes', <>Cookies estritamente necessários podem manter sessão, segurança e preferências. Cookies de análise ou personalização somente devem ser ativados após escolha válida quando exigido. O usuário poderá aceitar, rejeitar ou revisar preferências. A desativação de cookies essenciais pode impedir funções de autenticação.</>],
  ['compartilhamento', 'Compartilhamento e operadores', <>Dados poderão ser tratados por fornecedores de hospedagem, banco de dados, monitoramento, comunicação e suporte, somente conforme instruções, contratos e medidas de segurança. O projeto prevê hospedagem na Vercel e banco PostgreSQL serverless; os fornecedores efetivamente utilizados deverão ser atualizados nesta política antes da operação pública. Não vendemos dados pessoais.</>],
  ['transferencia', 'Transferência internacional', <>Fornecedores de infraestrutura podem processar dados fora do Brasil. Quando isso ocorrer, serão observados os mecanismos admitidos pela LGPD e pela regulamentação da ANPD, com avaliação do fornecedor, medidas contratuais e transparência ao titular.</>],
  ['retencao', 'Retenção e eliminação', <>Os dados serão mantidos apenas pelo tempo necessário às finalidades informadas, à manutenção da conta, ao cumprimento de obrigações legais, à segurança e ao exercício de direitos. Após o término, serão eliminados ou anonimizados, salvo conservação autorizada pelo art. 16 da LGPD. Prazos específicos deverão constar do registro interno de operações antes da entrada em produção.</>],
  ['seguranca', 'Segurança da informação', <>São previstas medidas como controle de acesso por perfil, hash de senhas, comunicação HTTPS, validação de entradas, registros de auditoria, cópias de segurança e revisão de permissões. Nenhum sistema é absolutamente seguro; incidentes relevantes serão avaliados e, quando exigido, comunicados à ANPD e aos titulares afetados.</>],
  ['direitos', 'Direitos do titular', <><p>Nos termos da LGPD, o titular pode solicitar gratuitamente:</p><ul><li>confirmação e acesso aos dados;</li><li>correção de dados incompletos, inexatos ou desatualizados;</li><li>anonimização, bloqueio ou eliminação de dados desnecessários, excessivos ou irregulares;</li><li>portabilidade, observada a regulamentação;</li><li>informação sobre compartilhamentos e sobre a possibilidade de negar consentimento;</li><li>eliminação de dados tratados com consentimento, ressalvadas as hipóteses legais;</li><li>revogação do consentimento e oposição a tratamento irregular;</li><li>revisão de decisões unicamente automatizadas que afetem seus interesses.</li></ul><p>A confirmação simplificada e o acesso serão fornecidos conforme os prazos legais. Poderemos solicitar informações para confirmar a identidade do requerente.</p></>],
  ['menores', 'Crianças e adolescentes', <>O tratamento de dados de crianças e adolescentes observará seu melhor interesse e as regras do art. 14 da LGPD. Quando necessário, será obtido consentimento específico e destacado de pelo menos um responsável legal, com esforços razoáveis de verificação. A plataforma não deve induzir o fornecimento de dados além do estritamente necessário.</>],
  ['decisoes', 'Decisões automatizadas', <>Notas, percentuais e feedbacks podem ser calculados automaticamente a partir das respostas do usuário. Esses resultados possuem finalidade educacional e não produzem efeitos jurídicos. O usuário poderá solicitar informações sobre os critérios e revisão quando uma decisão automatizada afetar seus interesses.</>],
  ['incidentes', 'Incidentes de segurança', <>Suspeitas de acesso indevido ou exposição de dados devem ser comunicadas pelo canal de contato. O CyberEduca+ investigará o evento, adotará medidas de contenção e manterá registros. Incidentes com risco ou dano relevante serão comunicados conforme a LGPD e as normas da ANPD.</>],
  ['alteracoes-privacidade', 'Atualizações da política', <>Esta política poderá ser atualizada para refletir mudanças legais, técnicas ou funcionais. Alterações relevantes serão destacadas e, quando necessário, será solicitado novo consentimento. Versão atual: <strong>22 de setembro de 2026</strong>.</>],
]

const termIndexItems = terms.map(([id, title], index) => [String(id), String(title), index + 1])
const privacyIndexItems = privacy.map(([id, title], index) => [String(id), String(title), index + 1])

function LegalCards({ items }: { items: (string | ReactNode)[][] }) {
  return <div className="legal-cards">{items.map(([id, title, content], index) => <article className="legal-card" id={String(id)} key={String(id)}><h2><span>{String(index + 1).padStart(2, '0')}</span>{title}</h2><div className="legal-copy">{content}</div></article>)}</div>
}

export function LegalPolicyContent({ loggedIn = false }: { loggedIn?: boolean }) {
  return <>{loggedIn ? <DashboardNavigation /> : <CyberHeader />}<main className={`legal-page${loggedIn ? ' legal-page-internal' : ''}`}>
    <aside className="legal-index"><p>Nesta página</p><nav><h2>Termos de Uso</h2>{termIndexItems.map(([id, label, number]) => <a href={`#${id}`} key={id}><span>{String(number).padStart(2, '0')}</span>{label}</a>)}<h2>Privacidade e LGPD</h2>{privacyIndexItems.map(([id, label, number]) => <a href={`#${id}`} key={id}><span>{String(number).padStart(2, '0')}</span>{label}</a>)}</nav></aside>
    <div className="legal-content">
      <section className="legal-section" id="termos-de-uso"><span className="legal-eyebrow">Termos de Uso</span><h1>Condições claras para uma experiência de aprendizagem segura</h1><p className="legal-lead">Estas regras explicam como utilizar o CyberEduca+ de forma responsável, segura e compatível com sua finalidade educacional.</p><LegalCards items={terms} /></section>
      <section className="legal-section legal-privacy" id="politica-de-privacidade"><span className="legal-eyebrow">Política de Privacidade e LGPD</span><h1>Transparência e controle sobre seus dados pessoais</h1><p className="legal-lead">Esta política descreve quais dados são tratados, por que são necessários, como são protegidos e como você pode exercer seus direitos.</p><LegalCards items={privacy} /></section>
      <footer className="legal-footer"><span>Última atualização: 22 de setembro de 2026</span></footer>
    </div>
  </main>{!loggedIn && <SiteFooter />}</>
}

export default function PoliticasPage() {
  return <LegalPolicyContent />
}
