export type Lesson = { slug: string; title: string; duration: string; status: 'completed' | 'current' | 'locked' }
export type Module = { title: string; lessons: Lesson[] }
export type Track = { slug: string; title: string; description: string; difficulty: 'Iniciante' | 'Intermediário' | 'Avançado'; modules: number; lessons: number; duration: string; progress: number; color: string; category: string; modulesData: Module[] }

export const tracks: Track[] = [
  { slug: 'fundamentos-cybersecurity', title: 'Fundamentos de Cybersecurity', description: 'Construa uma base sólida para entender ameaças, redes e os princípios essenciais da segurança da informação.', difficulty: 'Iniciante', modules: 4, lessons: 18, duration: '6h 30min', progress: 72, color: '#b7ff2a', category: 'Fundamentos', modulesData: [
    { title: 'Mentalidade de segurança', lessons: [{ slug: 'o-que-e-cybersecurity', title: 'O que é Cybersecurity?', duration: '18 min', status: 'completed' }, { slug: 'principios-da-seguranca', title: 'Princípios da segurança', duration: '24 min', status: 'completed' }, { slug: 'mapa-de-ameacas', title: 'Mapa de ameaças', duration: '20 min', status: 'current' }] },
    { title: 'Redes e protocolos', lessons: [{ slug: 'como-a-internet-funciona', title: 'Como a internet funciona', duration: '28 min', status: 'locked' }, { slug: 'modelo-osi', title: 'Modelo OSI na prática', duration: '31 min', status: 'locked' }, { slug: 'leitura-de-pacotes', title: 'Leitura de pacotes', duration: '26 min', status: 'locked' }] },
    { title: 'Sistemas operacionais', lessons: [{ slug: 'linux-para-seguranca', title: 'Linux para segurança', duration: '35 min', status: 'locked' }, { slug: 'permissoes-e-processos', title: 'Permissões e processos', duration: '29 min', status: 'locked' }] },
  ] },
  { slug: 'ethical-hacking', title: 'Ethical Hacking', description: 'Aprenda a pensar como um atacante, encontrar vulnerabilidades e reportar descobertas com responsabilidade.', difficulty: 'Intermediário', modules: 6, lessons: 32, duration: '12h 10min', progress: 38, color: '#57b8ff', category: 'Ofensiva', modulesData: [{ title: 'Reconhecimento', lessons: [{ slug: 'metodologia', title: 'Metodologia de pentest', duration: '22 min', status: 'completed' }, { slug: 'enumeracao', title: 'Enumeração de serviços', duration: '34 min', status: 'current' }] }, { title: 'Exploração web', lessons: [{ slug: 'owasp-top-ten', title: 'OWASP Top 10', duration: '41 min', status: 'locked' }, { slug: 'injection', title: 'Injeções na prática', duration: '38 min', status: 'locked' }] }] },
  { slug: 'defesa-e-resposta', title: 'Defesa e Resposta a Incidentes', description: 'Domine monitoramento, análise de sinais e resposta coordenada para reduzir o impacto de incidentes.', difficulty: 'Avançado', modules: 5, lessons: 24, duration: '9h 45min', progress: 14, color: '#ffbd52', category: 'Defensiva', modulesData: [{ title: 'Operações de defesa', lessons: [{ slug: 'blue-team', title: 'A mentalidade Blue Team', duration: '26 min', status: 'completed' }, { slug: 'triagem-alertas', title: 'Triagem de alertas', duration: '30 min', status: 'current' }] }, { title: 'Resposta a incidentes', lessons: [{ slug: 'primeiras-acoes', title: 'As primeiras ações', duration: '35 min', status: 'locked' }] }] },
  { slug: 'seguranca-cloud', title: 'Segurança em Cloud', description: 'Explore os fundamentos para proteger identidades, dados e workloads em ambientes cloud modernos.', difficulty: 'Intermediário', modules: 4, lessons: 20, duration: '7h 20min', progress: 100, color: '#d987ff', category: 'Cloud', modulesData: [{ title: 'Cloud foundations', lessons: [{ slug: 'shared-responsibility', title: 'Modelo de responsabilidade compartilhada', duration: '24 min', status: 'completed' }, { slug: 'iam-cloud', title: 'IAM em cloud', duration: '29 min', status: 'completed' }] }] },
]

export const allLessons = tracks.flatMap((track) => track.modulesData.flatMap((module) => module.lessons.map((lesson) => ({ ...lesson, track }))))
export const getTrack = (slug: string) => tracks.find((track) => track.slug === slug)
export const getLesson = (slug: string) => allLessons.find((lesson) => lesson.slug === slug)

export const stats = { completed: 27, inProgress: 3, finished: 1, overall: 64 }
