'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowLeft, ArrowRight, Check, Clock3, Menu, Share2 } from 'lucide-react'
import { CyberHeader } from '@/components/cyber-header'
import { getLesson, allLessons } from '@/lib/learning-data'

export default function LessonPage({ params }: { params: { slug: string } }) {
  const lesson = getLesson(params.slug) ?? allLessons[0]; const [done, setDone] = useState(lesson.status === 'completed'); const index = allLessons.findIndex((item) => item.slug === lesson.slug); const previous = allLessons[index - 1]; const next = allLessons[index + 1]
  return <main className="app-shell"><CyberHeader /><div className="lesson-layout"><aside className="lesson-sidebar"><Link href={`/trilhas/${lesson.track.slug}`} className="back-link"><ArrowLeft size={16} /> Voltar para a trilha</Link><div className="sidebar-track"><span className="eyebrow">Trilha atual</span><h2>{lesson.track.title}</h2><div className="progress-track"><span style={{ width: `${lesson.track.progress}%` }} /></div><span>{lesson.track.progress}% concluído</span></div><nav><span className="sidebar-label">Conteúdo</span>{lesson.track.modulesData.map((module) => <div key={module.title}><strong>{module.title}</strong>{module.lessons.map((item) => <Link key={item.slug} className={item.slug === lesson.slug ? 'lesson-nav-active' : ''} href={`/aulas/${item.slug}`}>{item.title}</Link>)}</div>)}</nav></aside><article className="lesson-content"><div className="lesson-topline"><span>Módulo 01 / Mentalidade de segurança</span><button><Share2 size={16} /> Compartilhar</button></div><div className="eyebrow">Aula {String(index + 1).padStart(2, '0')}</div><h1>{lesson.title}</h1><div className="lesson-meta"><span><Clock3 size={16} /> {lesson.duration} de leitura</span><span><Menu size={16} /> Fundamentos de Cybersecurity</span></div><div className="lesson-divider" /><div className="prose-content"><p className="lead">A segurança começa antes da primeira ferramenta. Começa pela forma como você observa um sistema, questiona suas suposições e transforma sinais em decisões.</p><h2>Por que este conceito importa?</h2><p>Em cybersecurity, o cenário muda todos os dias. Novas tecnologias criam novas superfícies de ataque, enquanto equipes precisam tomar decisões rápidas com informações incompletas.</p><div className="lesson-callout"><ShieldIcon /><div><strong>Insight da aula</strong><p>Um bom profissional de segurança não tenta prever todos os ataques. Ele constrói sistemas preparados para detectar, responder e aprender com cada tentativa.</p></div></div><h2>Segurança como processo contínuo</h2><p>O trabalho começa entendendo o contexto do negócio, os ativos mais importantes e os riscos que realmente podem causar impacto. A partir daí, cada camada de proteção deve ser testada e melhorada continuamente.</p><ul><li>Conheça os ativos que precisam ser protegidos.</li><li>Entenda as ameaças relevantes para o contexto.</li><li>Teste suas defesas em cenários realistas.</li></ul></div><div className="lesson-actions"><button className={`complete-button ${done ? 'is-done' : ''}`} onClick={() => setDone(!done)}>{done ? <><Check size={18} /> Aula concluída</> : 'Marcar como concluída'}</button><div className="lesson-nav-buttons">{previous && <Link href={`/aulas/${previous.slug}`}><ArrowLeft size={16} /> Anterior</Link>}{next && <Link href={`/aulas/${next.slug}`}>Próxima aula <ArrowRight size={16} /></Link>}</div></div></article></div></main>
}
function ShieldIcon() { return <span className="callout-icon"><span>+</span></span> }
